name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
         # Specify the subdirectory of the server 'backend/server'
        with:
          sparse-checkout: |
            backend/server

      # Set up Cloud SDK 
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }} 

        # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGISTRY_DOMAIN }} --quiet  

      # Build your Docker image
      - name: Build Docker image
        working-directory: backend/server
        run: |
          docker build -t ${{ secrets.GCP_REGISTRY_PATH }}/presently-server:${{ github.sha }} .
           
      # Push the Docker image to GCR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.GCP_REGISTRY_PATH }}/presently-server:${{ github.sha }}

      # Optionally, deploy the image to a service like Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy presently \
          --image ${{ secrets.GCP_REGISTRY_PATH }}/presently-server:${{ github.sha }} \
          --region ${{ secrets.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated
