name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
         # Specify the subdirectory of the server 'backend/server'
        with:
          sparse-checkout: |
            backend/server

      # Set up Cloud SDK and authenticate with GCP
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: annular-climate-455110-j8

        # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet  

      # Build your Docker image
      - name: Build Docker image
        working-directory: backend/server
        run: |
          docker build -t asia-south1-docker.pkg.dev/annular-climate-455110-j8/presently-repo/presently-server:${{ github.sha }} .
      
# Authenticate Docker to push to Google Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin asia-south1-docker.pkg.dev
      
      # Push the Docker image to GCR
      - name: Push Docker image
        run: |
          docker push asia-south1-docker.pkg.dev/annular-climate-455110-j8/presently-repo/presently-server:${{ github.sha }}

      # Optionally, deploy the image to a service like Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-service-name \
          --image asia-south1-docker.pkg.dev/annular-climate-455110-j8/presently-repo/presently-server:${{ github.sha }} \
          --region asia-south1 \
          --platform managed \
          --allow-unauthenticated
